// Define action types

export const ADD_TODO = 'ADD_TODO'
// ... more
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM'
export const UPDATE_CITY = 'UPDATE_CITY'
export const UPDATE_STATE_CHOICE = 'UPDATE_STATE_CHOICE'

export const FETCHING_DATA = 'FETCHING_DATA'
export const RECEIVED_DATA = 'RECEIVED_DATA'
export const RECEIVED_ERROR = 'RECEIVED_ERROR'

//Signup
export const SIGNUP_UPDATE_FIRSTNAME = 'SIGNUP_UPDATE_FIRSTNAME'
export const SIGNUP_UPDATE_LASTNAME = 'SIGNUP_UPDATE_LASTNAME'
export const SIGNUP_UPDATE_EMAILADDR = 'SIGNUP_UPDATE_EMAILADDR'
export const SIGNUP_UPDATE_USERNAME = 'SIGNUP_UPDATE_USERNAME'
export const SIGNUP_UPDATE_PASSWORD = 'SIGNUP_UPDATE_PASSWORD'
export const RECEIVED_SIGNUP_DATA = 'RECEIVED_SIGNUP_DATA'
export const RECEIVED_SIGNUP_ERROR = 'RECEIVED_SIGNUP_ERROR'